### ISSUE TITLE
Error when using `lovesay` on Fedora

### ISSUE THREAD

**Issue by OlaoluwaM** [ZenithDS/lovesay#5]
### Problem
I installed `lovesay` via `pip3` as specified in the README, but when I tried to run it I got this error
![image](https://user-images.githubusercontent.com/37044906/155886648-c7705bfb-6541-49e9-95dd-31177c734463.png)

![image](https://user-images.githubusercontent.com/37044906/155886771-70a4ea6a-614e-441c-be9e-a233c271e32a.png)

I created the `$HOME/.config/lovesay/quotes` file and have two quotes in it
![image](https://user-images.githubusercontent.com/37044906/155886706-11e2ffd8-949b-421c-91f6-f7f17f892eda.png)

### System Info
- OS: Fedora 35

**Comment by ZenithDS** [comment]
Hi! lovesay is intended to display a quote for each day of the month, so it looks like it's throwing an error since it's trying to find a quote for 27th day and there aren't any since your file only has two quotes. Regardless, it should've been handled on my end. I've pushed out a hot fix where it should print out an empty heart if there is no quote for the current day, but I'll look into a more elegant solution soon enough :)

**Comment by OlaoluwaM** [comment]
Oh interesting, but why not default to a random quote?

**Comment by ZenithDS** [comment]
I certainly thought of that at one point, I just figured printing out an empty heart was the easiest way to let the users know something was wrong. but perhaps making the quote an error message letting the user know what to fix would be a better idea?

**Comment by ZenithDS** [comment]
I've pushed out an update to print "No quote found for today, here's a hug :)" if there is no quote for the current day. Not having a quotes file still prints out an empty heart, but with the new update, lovesay can also print out on-demand messages. 

For example: 
```sh
lovesay "hello world"
```
prints out:

<img width="1440" alt="lovesay" src="https://user-images.githubusercontent.com/77712443/156017284-e433b859-8f24-45d3-bb3c-9a073e2746f3.png">
