### ISSUE TITLE
Error with piping

### ISSUE THREAD

**Issue by Literal-Eval** [ZenithDS/lovesay#7]
Is this program not configured to work with pipes ? Gives an error every time. Also, gives the same error when added to startup script of fish shell (not tested on bashrc)

**Comment by ZenithDS** [comment]
Hi! sadly, lovesay currently does not support pipes but making lovesay behave like a proper unix program is high up on the to-do list. Would you mind providing info/screenshot on how you're trying to use lovesay with pipes and the error it throws? 

As for using lovesay in a startup script, I'm really now sure why that would be the case since I've been using lovesay in my .zshrc for quite some time. Would you mind showing how lovesay is being called in your startup script?

**Comment by Literal-Eval** [comment]
![lovesay_error_one](https://user-images.githubusercontent.com/62198564/156991263-2d511c82-2d4a-4f43-a0e6-9f9c528f3764.png)

This is the error.

Also I am interested in contributing to this project (if you need help :) ).

**Comment by ZenithDS** [comment]
This turned out to be a rather easy fix and with lovesay 0.2.5, piping should no longer be an issue! Please let me know if the issue still persists. I also appreciate the offer to help, I don't think there is much else to be done but I do appreciate you opening this issue and helping me fix the edge cases :)

**Comment by Literal-Eval** [comment]
Works. Closing this issue.
Ping me if you need help on something.
